# Generated by Django 3.2.4 on 2021-06-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'The Account', 'verbose_name_plural': 'List Account'},
        ),
    ]
